package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AdditionalStructures implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String pool;
   private java.lang.String garage;
   private java.lang.String trampoline;

   public AdditionalStructures()
   {
   }

   public java.lang.String getPool()
   {
      return this.pool;
   }

   public void setPool(java.lang.String pool)
   {
      this.pool = pool;
   }

   public java.lang.String getGarage()
   {
      return this.garage;
   }

   public void setGarage(java.lang.String garage)
   {
      this.garage = garage;
   }

   public java.lang.String getTrampoline()
   {
      return this.trampoline;
   }

   public void setTrampoline(java.lang.String trampoline)
   {
      this.trampoline = trampoline;
   }

   public AdditionalStructures(java.lang.String pool, java.lang.String garage,
         java.lang.String trampoline)
   {
      this.pool = pool;
      this.garage = garage;
      this.trampoline = trampoline;
   }

}