package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Alarm implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String burglar;
   private java.lang.String fire;

   public Alarm()
   {
   }

   public java.lang.String getBurglar()
   {
      return this.burglar;
   }

   public void setBurglar(java.lang.String burglar)
   {
      this.burglar = burglar;
   }

   public java.lang.String getFire()
   {
      return this.fire;
   }

   public void setFire(java.lang.String fire)
   {
      this.fire = fire;
   }

   public Alarm(java.lang.String burglar, java.lang.String fire)
   {
      this.burglar = burglar;
      this.fire = fire;
   }

}