package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AmInt implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer otherStructureLimit;
   private java.lang.Integer propertyClaims;

   private java.lang.Integer electricalUpdate;

   private java.lang.Integer yearBuilt;

   private java.lang.Integer per_of_flat_roof;

   private java.lang.Integer garageCarportType;

   private java.lang.Integer priorClaims;

   private java.lang.String alarm;

   private java.lang.String secured_community;

   public AmInt()
   {
   }

   public java.lang.Integer getOtherStructureLimit()
   {
      return this.otherStructureLimit;
   }

   public void setOtherStructureLimit(java.lang.Integer otherStructureLimit)
   {
      this.otherStructureLimit = otherStructureLimit;
   }

   public java.lang.Integer getPropertyClaims()
   {
      return this.propertyClaims;
   }

   public void setPropertyClaims(java.lang.Integer propertyClaims)
   {
      this.propertyClaims = propertyClaims;
   }

   public java.lang.Integer getElectricalUpdate()
   {
      return this.electricalUpdate;
   }

   public void setElectricalUpdate(java.lang.Integer electricalUpdate)
   {
      this.electricalUpdate = electricalUpdate;
   }

   public java.lang.Integer getYearBuilt()
   {
      return this.yearBuilt;
   }

   public void setYearBuilt(java.lang.Integer yearBuilt)
   {
      this.yearBuilt = yearBuilt;
   }

   public java.lang.Integer getPer_of_flat_roof()
   {
      return this.per_of_flat_roof;
   }

   public void setPer_of_flat_roof(java.lang.Integer per_of_flat_roof)
   {
      this.per_of_flat_roof = per_of_flat_roof;
   }

   public java.lang.Integer getGarageCarportType()
   {
      return this.garageCarportType;
   }

   public void setGarageCarportType(java.lang.Integer garageCarportType)
   {
      this.garageCarportType = garageCarportType;
   }

   public java.lang.Integer getPriorClaims()
   {
      return this.priorClaims;
   }

   public void setPriorClaims(java.lang.Integer priorClaims)
   {
      this.priorClaims = priorClaims;
   }

   public java.lang.String getAlarm()
   {
      return this.alarm;
   }

   public void setAlarm(java.lang.String alarm)
   {
      this.alarm = alarm;
   }

   public java.lang.String getSecured_community()
   {
      return this.secured_community;
   }

   public void setSecured_community(java.lang.String secured_community)
   {
      this.secured_community = secured_community;
   }

   public AmInt(java.lang.Integer otherStructureLimit,
         java.lang.Integer propertyClaims, java.lang.Integer electricalUpdate,
         java.lang.Integer yearBuilt, java.lang.Integer per_of_flat_roof,
         java.lang.Integer garageCarportType, java.lang.Integer priorClaims,
         java.lang.String alarm, java.lang.String secured_community)
   {
      this.otherStructureLimit = otherStructureLimit;
      this.propertyClaims = propertyClaims;
      this.electricalUpdate = electricalUpdate;
      this.yearBuilt = yearBuilt;
      this.per_of_flat_roof = per_of_flat_roof;
      this.garageCarportType = garageCarportType;
      this.priorClaims = priorClaims;
      this.alarm = alarm;
      this.secured_community = secured_community;
   }

}