package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Condominium implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String houseType;

   public Condominium()
   {
   }

   public java.lang.String getHouseType()
   {
      return this.houseType;
   }

   public void setHouseType(java.lang.String houseType)
   {
      this.houseType = houseType;
   }

   public Condominium(java.lang.String houseType)
   {
      this.houseType = houseType;
   }

}