package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CurrentCoverage implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String currentCoverageHomeowner;

   public CurrentCoverage()
   {
   }

   public java.lang.String getCurrentCoverageHomeowner()
   {
      return this.currentCoverageHomeowner;
   }

   public void setCurrentCoverageHomeowner(
         java.lang.String currentCoverageHomeowner)
   {
      this.currentCoverageHomeowner = currentCoverageHomeowner;
   }

   public CurrentCoverage(java.lang.String currentCoverageHomeowner)
   {
      this.currentCoverageHomeowner = currentCoverageHomeowner;
   }

}