package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerCome implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String customerCome;

   public CustomerCome()
   {
   }

   public java.lang.String getCustomerCome()
   {
      return this.customerCome;
   }

   public void setCustomerCome(java.lang.String customerCome)
   {
      this.customerCome = customerCome;
   }

   public CustomerCome(java.lang.String customerCome)
   {
      this.customerCome = customerCome;
   }

}