package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Dog implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String dogBreed;

   public Dog()
   {
   }

   public java.lang.String getDogBreed()
   {
      return this.dogBreed;
   }

   public void setDogBreed(java.lang.String dogBreed)
   {
      this.dogBreed = dogBreed;
   }

   public Dog(java.lang.String dogBreed)
   {
      this.dogBreed = dogBreed;
   }

}