package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Dog implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String dogBreeds;

   public Dog()
   {
   }

   public java.lang.String getDogBreeds()
   {
      return this.dogBreeds;
   }

   public void setDogBreeds(java.lang.String dogBreeds)
   {
      this.dogBreeds = dogBreeds;
   }

   public Dog(java.lang.String dogBreeds)
   {
      this.dogBreeds = dogBreeds;
   }

}