package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FourPoint implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String fourPoint;

   public FourPoint()
   {
   }

   public java.lang.String getFourPoint()
   {
      return this.fourPoint;
   }

   public void setFourPoint(java.lang.String fourPoint)
   {
      this.fourPoint = fourPoint;
   }

   public FourPoint(java.lang.String fourPoint)
   {
      this.fourPoint = fourPoint;
   }

}