package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Heating implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Heating() {
    }

}