package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HomeBusiness implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String bussinesInHome;
   private java.lang.String customerCome;

   public HomeBusiness()
   {
   }

   public java.lang.String getBussinesInHome()
   {
      return this.bussinesInHome;
   }

   public void setBussinesInHome(java.lang.String bussinesInHome)
   {
      this.bussinesInHome = bussinesInHome;
   }

   public java.lang.String getCustomerCome()
   {
      return this.customerCome;
   }

   public void setCustomerCome(java.lang.String customerCome)
   {
      this.customerCome = customerCome;
   }

   public HomeBusiness(java.lang.String bussinesInHome,
         java.lang.String customerCome)
   {
      this.bussinesInHome = bussinesInHome;
      this.customerCome = customerCome;
   }

}