package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OtherDetails implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String dog;
   private java.lang.String horse;
   private java.lang.String livestock;

   public OtherDetails()
   {
   }

   public java.lang.String getDog()
   {
      return this.dog;
   }

   public void setDog(java.lang.String dog)
   {
      this.dog = dog;
   }

   public java.lang.String getHorse()
   {
      return this.horse;
   }

   public void setHorse(java.lang.String horse)
   {
      this.horse = horse;
   }

   public java.lang.String getLivestock()
   {
      return this.livestock;
   }

   public void setLivestock(java.lang.String livestock)
   {
      this.livestock = livestock;
   }

   public OtherDetails(java.lang.String dog, java.lang.String horse,
         java.lang.String livestock)
   {
      this.dog = dog;
      this.horse = horse;
      this.livestock = livestock;
   }

}