package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Ownership implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer timeOwnership;

   public Ownership()
   {
   }

   public java.lang.Integer getTimeOwnership()
   {
      return this.timeOwnership;
   }

   public void setTimeOwnership(java.lang.Integer timeOwnership)
   {
      this.timeOwnership = timeOwnership;
   }

   public Ownership(java.lang.Integer timeOwnership)
   {
      this.timeOwnership = timeOwnership;
   }

}