package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Page2 implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String unrepairedDamage;
   private java.lang.String activelyRepairing;
   private java.lang.String hadForeclosure;
   private java.lang.String hadBankruptcy;

   public Page2()
   {
   }

   public java.lang.String getUnrepairedDamage()
   {
      return this.unrepairedDamage;
   }

   public void setUnrepairedDamage(java.lang.String unrepairedDamage)
   {
      this.unrepairedDamage = unrepairedDamage;
   }

   public java.lang.String getActivelyRepairing()
   {
      return this.activelyRepairing;
   }

   public void setActivelyRepairing(java.lang.String activelyRepairing)
   {
      this.activelyRepairing = activelyRepairing;
   }

   public java.lang.String getHadForeclosure()
   {
      return this.hadForeclosure;
   }

   public void setHadForeclosure(java.lang.String hadForeclosure)
   {
      this.hadForeclosure = hadForeclosure;
   }

   public java.lang.String getHadBankruptcy()
   {
      return this.hadBankruptcy;
   }

   public void setHadBankruptcy(java.lang.String hadBankruptcy)
   {
      this.hadBankruptcy = hadBankruptcy;
   }

   public Page2(java.lang.String unrepairedDamage,
         java.lang.String activelyRepairing,
         java.lang.String hadForeclosure, java.lang.String hadBankruptcy)
   {
      this.unrepairedDamage = unrepairedDamage;
      this.activelyRepairing = activelyRepairing;
      this.hadForeclosure = hadForeclosure;
      this.hadBankruptcy = hadBankruptcy;
   }

}