package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Replumb implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String fullyReplumb;

   public Replumb()
   {
   }

   public java.lang.String getFullyReplumb()
   {
      return this.fullyReplumb;
   }

   public void setFullyReplumb(java.lang.String fullyReplumb)
   {
      this.fullyReplumb = fullyReplumb;
   }

   public Replumb(java.lang.String fullyReplumb)
   {
      this.fullyReplumb = fullyReplumb;
   }

}