package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WallConstruction implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public WallConstruction() {
    }

}