package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WindMitigation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String windMitigation;

   public WindMitigation()
   {
   }

   public java.lang.String getWindMitigation()
   {
      return this.windMitigation;
   }

   public void setWindMitigation(java.lang.String windMitigation)
   {
      this.windMitigation = windMitigation;
   }

   public WindMitigation(java.lang.String windMitigation)
   {
      this.windMitigation = windMitigation;
   }

}