package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class YearOfConstruction implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer yearOfConstruction;

   public YearOfConstruction()
   {
   }

   public java.lang.Integer getYearOfConstruction()
   {
      return this.yearOfConstruction;
   }

   public void setYearOfConstruction(java.lang.Integer yearOfConstruction)
   {
      this.yearOfConstruction = yearOfConstruction;
   }

   public YearOfConstruction(java.lang.Integer yearOfConstruction)
   {
      this.yearOfConstruction = yearOfConstruction;
   }

}