package org.brms.myproject;
global java.util.List list;
//global org.slf4j.Logger logger;
rule "AmInt: Approve Other structures"
    when
        AmInt((GarageType=="detachedSeperatedtructureWithoutLivingSpace")||(GarageType=="attachedToTheMainHouse"))
    then
        list.add("Other Structure limit");
        System.out.println("@AmInt: Other Structure limit eligible");
    end

rule "check age of construction"
    when
        AmInt(((2018-yearBuilt)>0)&&((2018-yearBuilt)<76))
    then
        list.add("@ Age of building");
        System.out.println("@ Age of building");
    end

