package org.brms.myproject;

//Approved rules

rule "ArkRoyal: Approve other structure eligibilty"
when
ArkRoyal((GarageType=="detachedSeperatedtructureWithoutLivingSpace")||(GarageType=="attachedToTheMainHouse"))
then
System.out.println("@ArkRoyal: Other Structure limit ");
end

rule "ArkRoyal:Approve secondary or seasonal occupancy"
when
ArkRoyal((secured_community=="Gated with a guard")||(secured_community=="Gated with an automated system"))
then
System.out.println("@ArkRoyal: Secondary/Seasonal");
end

rule "ArkRoyal: Approve masonary to frame ratio"
when	
ArkRoyal(masonryFrame=="Masonry 76% or more - Frame 24%")
then
System.out.println("@ArkRoyal: Masonary frame ratio");
end

rule "ArkRoyal: Approve Composition Shingle roof"
when
ArkRoyal((RoofMaterial=="Comp_Shingle")&&((2018-yearBuilt)>-1)&&((2018-yearBuilt)<16))	
then
System.out.println("@ArkRoyal: Composition Shingle roof");
end

rule "ArkRoyal: Approve dog breeds policy"
when
d:Dog((dogBreed!="Pit Bulls")&&(dogBreed!= "German Shepherd")&&(dogBreed!= "Akitas")&&(dogBreed!= "Doberman Pinschers")&&(dogBreed!= "Chows")&&(dogBreed!= "Rottweilers")&&(dogBreed!= "Great Danes")&&(dogBreed!= "Caucasian Mountain Dogs")&&(dogBreed!= "Staffordshire Terriers")&&(dogBreed!= "American Bulldogs")&&(dogBreed!= "Beaucerons")&&(dogBreed!= "Wolf Hybrids"))
then
System.out.println("@ArkRoyal: Dog breed policy"+ d.getDogBreed());
end

rule "ArkRoyal: Approve dog breeds endorsement"
when
d:Dog((dogBreed!="Pit Bulls")&&(dogBreed!= "German Shepherd")&&(dogBreed!= "Akitas")&&(dogBreed!= "Doberman Pinschers")&&(dogBreed!= "Chows")&&(dogBreed!= "Rottweilers")&&(dogBreed!= "Great Danes")&&(dogBreed!= "Caucasian Mountain Dogs")&&(dogBreed!= "Staffordshire Terriers")&&(dogBreed!= "American Bulldogs")&&(dogBreed!= "Beaucerons")&&(dogBreed!= "Wolf Hybrids"))
then
System.out.println("@ArkRoyal: Dog breed endorsement"+ d.getDogBreed());
end



// Declined rules

rule "ArkRoyal: Decline diving board"
when	
ArkRoyal(DivingBoard=="yes")
then
System.out.println("#ArkRoyal: Diving board");
end

rule "ArkRoyal: Decline pool slide"
when
ArkRoyal(PoolSlide=="yes")
then
System.out.println("#ArkRoyal: PoolSlide");
end

rule "ArkRoyal: Decline trampoline"
when	
ArkRoyal(trampoline==true)
then
System.out.println("#ArkRoyal: Trampoline");
end 

rule "ArkRoyal: Decline Composition Shingle roof"
when
ArkRoyal((RoofMaterial=="Comp-Shingle")&&((2018-yearBuilt)>15))	
then
System.out.println("#ArkRoyal: Composition Shingle roof");
end

rule "ArkRoyal: Decline dog breeds policy"
when
d:Dog((dogBreed=="Pit Bulls")||(dogBreed== "German Shepherd")||(dogBreed== "Akitas")||(dogBreed== "Doberman Pinschers")||(dogBreed== "Chows")||(dogBreed== "Rottweilers")||(dogBreed== "Great Danes")||(dogBreed== "Caucasian Mountain Dogs")||(dogBreed== "Staffordshire Terriers")||(dogBreed== "American Bulldogs")||(dogBreed== "Beaucerons")||(dogBreed== "Wolf Hybrids"))
then
System.out.println("#ArkRoyal: Dog breeds policy "+d.getDogBreed());
end

rule "ArkRoyal: Decline dog breeds endorsement"
when
d:Dog((dogBreed=="Pit Bulls")||(dogBreed== "German Shepherd")||(dogBreed== "Akitas")||(dogBreed== "Doberman Pinschers")||(dogBreed== "Chows")||(dogBreed== "Rottweilers")||(dogBreed== "Great Danes")||(dogBreed== "Caucasian Mountain Dogs")||(dogBreed== "Staffordshire Terriers")||(dogBreed== "American Bulldogs")||(dogBreed== "Beaucerons")||(dogBreed== "Wolf Hybrids"))
then
System.out.println("#ArkRoyal: Dog breeds endorsement "+d.getDogBreed());
end


