package org.brms.myproject;

//Approved rules

rule "ASI: Approve other structure eligibilty"
when
ASI((GarageType=="detachedSeperatedtructureWithoutLivingSpace")||(GarageType=="attachedToTheMainHouse"))
then
System.out.println("@ASI: Other Structure limit ");
end

rule "ASI:Approve secondary or seasonal occupancy"
when
ASI((secured_community=="Gated with a guard")||(secured_community=="Gated with an automated system"))
then
System.out.println("@ASI: Secondary/Seasonal");
end

rule "ASI: Approve masonary to frame ratio"
when	
ASI(masonryFrame=="Masonry 76% or more - Frame 24%")
then
System.out.println("@ASI: Masonary frame ratio");
end

rule "ASI: Approve Composition Shingle roof"
when
ASI((RoofMaterial=="Comp_Shingle")&&((2018-yearBuilt)>-1)&&((2018-yearBuilt)<16))	
then
System.out.println("@ASI: Composition Shingle roof");
end

rule "ASI: Approve dog breeds policy"
when
d:Dog((dogBreed!="Pit Bulls")&&(dogBreed!= "German Shepherd")&&(dogBreed!= "Akitas")&&(dogBreed!= "Doberman Pinschers")&&(dogBreed!= "Chows")&&(dogBreed!= "Rottweilers")&&(dogBreed!= "Great Danes")&&(dogBreed!= "Caucasian Mountain Dogs")&&(dogBreed!= "Staffordshire Terriers")&&(dogBreed!= "American Bulldogs")&&(dogBreed!= "Beaucerons")&&(dogBreed!= "Wolf Hybrids"))
then
System.out.println("@ASI: Dog breed policy"+ d.getDogBreed());
end

rule "ASI: Approve dog breeds endorsement"
when
d:Dog((dogBreed!="Pit Bulls")&&(dogBreed!= "German Shepherd")&&(dogBreed!= "Akitas")&&(dogBreed!= "Doberman Pinschers")&&(dogBreed!= "Chows")&&(dogBreed!= "Rottweilers")&&(dogBreed!= "Great Danes")&&(dogBreed!= "Caucasian Mountain Dogs")&&(dogBreed!= "Staffordshire Terriers")&&(dogBreed!= "American Bulldogs")&&(dogBreed!= "Beaucerons")&&(dogBreed!= "Wolf Hybrids"))
then
System.out.println("@ASI: Dog breed endorsement"+ d.getDogBreed());
end



// Declined rules

rule "ASI: Decline diving board"
when	
ASI(DivingBoard=="yes")
then
System.out.println("#ASI: Diving board");
end

rule "ASI: Decline pool slide"
when
ASI(PoolSlide=="yes")
then
System.out.println("#ASI: PoolSlide");
end

rule "ASI: Decline trampoline"
when	
ASI(trampoline==true)
then
System.out.println("#ASI: Trampoline");
end 

rule "ASI: Decline Composition Shingle roof"
when
ASI((RoofMaterial=="Comp-Shingle")&&((2018-yearBuilt)>15))	
then
System.out.println("#ASI: Composition Shingle roof");
end

rule "ASI: Decline dog breeds policy"
when
d:Dog((dogBreed=="Pit Bulls")||(dogBreed== "German Shepherd")||(dogBreed== "Akitas")||(dogBreed== "Doberman Pinschers")||(dogBreed== "Chows")||(dogBreed== "Rottweilers")||(dogBreed== "Great Danes")||(dogBreed== "Caucasian Mountain Dogs")||(dogBreed== "Staffordshire Terriers")||(dogBreed== "American Bulldogs")||(dogBreed== "Beaucerons")||(dogBreed== "Wolf Hybrids"))
then
System.out.println("#ASI: Dog breeds policy "+d.getDogBreed());
end

rule "ASI: Decline dog breeds endorsement"
when
d:Dog((dogBreed=="Pit Bulls")||(dogBreed== "German Shepherd")||(dogBreed== "Akitas")||(dogBreed== "Doberman Pinschers")||(dogBreed== "Chows")||(dogBreed== "Rottweilers")||(dogBreed== "Great Danes")||(dogBreed== "Caucasian Mountain Dogs")||(dogBreed== "Staffordshire Terriers")||(dogBreed== "American Bulldogs")||(dogBreed== "Beaucerons")||(dogBreed== "Wolf Hybrids"))
then
System.out.println("#ASI: Dog breeds endorsement "+d.getDogBreed());
end


