package org.brms.myproject;
rule "check wether the house type is condominium"
when
StructureType((houseType == "Condominium")&&(houseType!="Residential")&&(houseType!="Row"))
then
System.out.println("How many stories is the building?");
drools.setFocus("Stories");
end
rule "Check number of stories 6 or above"
ruleflow-group "Stories"
when
StructureType(stories>5)
then
System .out.println("lock superior");
end