package org.brms.myproject;
rule "Check whether Constructed before 30 years"
when
YearOfConstruction((yearOfConstruction<2001)&&(yearOfConstruction>1987))
then
System.out.println("check whether construct before 30 years");
drools.setFocus("Year of construction");
end
rule "check whether construsted after 2001"
ruleflow-group "Year of construction"
when
YearOfConstruction(yearOfConstruction<1988)
then
System.out.println("Display the options");
drools.setFocus("Year of construction");
end
