package org.brms.myproject;
rule "Check whether Constructed not before 30 years"
when
YearOfConstruction((yearOfConstruction>1987)||(yearOfConstruction==2018))
then
System.out.println("check whether constructed before 2001");
drools.setFocus("Year of construction");
end
rule "check whether year of construction is 2018"
ruleflow-group "Year of construction"
when
YearOfConstruction(yearOfConstruction==2018)
then
System.out.println("Display the options");
drools.setFocus("Year of construction");
end
rule "check whether construsted before 2001"
ruleflow-group "Year of construction"
when
YearOfConstruction((yearOfConstruction<2001)||(yearOfConstruction==2018))
then
System.out.println("Display the options");
end

