package org.brms.myproject;
global org.slf4j.Logger logger;
rule "Check whether Constructed not before 30 years"
when
YearOfConstruction((yearOfConstruction>1987)||(yearOfConstruction==2018))
then
System.out.println("Constructed not before 30 years");
drools.setFocus("Year of construction");
end
rule "check whether year of construction is 2018"
ruleflow-group "Year of construction"
when
YearOfConstruction(yearOfConstruction==2018)
then
System.out.println("Constructed in 2018");
drools.setFocus("Year of construction");
end
rule "check whether construsted before 2001"
ruleflow-group "Year of construction"
when
YearOfConstruction((yearOfConstruction<2001)||(yearOfConstruction==2018))
then
System.out.println("Constructed before 2001");
end

